# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
